// workers/system-update/logic.ts — pure logic, usable from Node CI and the browser.
import type { Reader, WorkerResult, ModuleEntry } from "../shared/reader";

export interface RunOpts {
  reader: Reader;
}

/**
 * Generate SYSTEM.md from the module tree the reader exposes.
 * - Empty tree → header-only.
 * - Non-empty   → header + per-module index (name, version, api, depends_on).
 */
export async function run({ reader }: RunOpts): Promise<WorkerResult> {
  const modules = await reader.listModules();
  const md = render(modules);
  return { ok: true, message: `indexed ${modules.length} module(s)`, details: { markdown: md } };
}

function render(modules: ModuleEntry[]): string {
  const lines: string[] = [
    "# SYSTEM.md",
    "",
    "> Machine-generated by `pnpm system:update`. Do not hand-edit.",
    "> A drift here is a CI blocker (STANDARDS §11).",
    "",
    "## Modules",
    "",
  ];
  if (modules.length === 0) {
    lines.push("_No modules registered yet._", "");
    return lines.join("\n");
  }
  for (const m of modules) {
    lines.push(
      `### ${m.yaml.name} \`${m.yaml.version}\``,
      "",
      `- **api:** \`${m.yaml.api}\``,
      `- **depends_on:** ${m.yaml.depends_on.length ? m.yaml.depends_on.join(", ") : "—"}`,
      `- **description:** ${m.yaml.description.replace(/\s+/g, " ").trim()}`,
      ""
    );
  }
  return lines.join("\n");
}
